export const RECEIVE_DATA = 'RECEIVE_DATA';

export const CREATE_FAVORITE = 'CREATE_FAVORITE';
export const DELETE_FAVORITE = 'DELETE_FAVORITE';
export const UPDATE_FAVORITE = 'UPDATE_FAVORITE';
export const REQUEST_FAVORITES = 'REQUEST_FAVORITES';
export const UPDATE_TAGS = 'UPDATE_TAGS';
export const TOGGLE_PIN = 'TOGGLE_PIN';
export const UPDATE_SETTINGS = 'UPDATE_SETTINGS';
