import { QueryState } from './types';
import KuaidiData from './kuaidi-map.json';

export const QueryStateMap: Record<string, string> = {
  [QueryState.InTransit]: '在途',
  [QueryState.InTransitCity]: '到达派件城市',
  [QueryState.InTransitRoad]: '干线',
  [QueryState.InTransitChange]: '转递',
  [QueryState.Accepted]: '揽收',
  [QueryState.AcceptedPending]: '已下单',
  [QueryState.AcceptedProcessing]: '待揽收',
  [QueryState.AcceptedCompleted]: '已揽收',
  [QueryState.Question]: '疑难',
  [QueryState.QuestionDeliveringTimeout]: '超时未签收',
  [QueryState.QuestionTimeout]: '超时未更新',
  [QueryState.QuestionReject]: '拒收',
  [QueryState.QuestionDelivering]: '派件异常',
  [QueryState.QuestionStation]: '柜或驿站超时未取',
  [QueryState.QuestionConact]: '无法联系',
  [QueryState.QuestionOut]: '超区',
  [QueryState.QuestionOnHold]: '滞留',
  [QueryState.QuestionDamage]: '破损',
  [QueryState.QuestionCancel]: '销单',
  [QueryState.Delivered]: '签收',
  [QueryState.DeliveredSelf]: '本人签收',
  [QueryState.DeliveredFailed]: '派件异常后签收',
  [QueryState.DeliveredOther]: '代签',
  [QueryState.DeliveredStation]: '投柜或站签收',
  [QueryState.Reject]: '退签',
  [QueryState.RejectDestory]: '已销单',
  [QueryState.RejectSelf]: '拒签',
  [QueryState.Delivering]: '派件',
  [QueryState.DeliveringStation]: '投柜或驿站',
  [QueryState.Return]: '退回',
  [QueryState.Transfer]: '转投',
  [QueryState.CheckPoint]: '清关',
  [QueryState.CheckPointPending]: '待清关',
  [QueryState.CheckPointProcessing]: '清关中',
  [QueryState.CheckPointCompleted]: '已清关',
  [QueryState.CheckPointError]: '清关异常',
};

export const KuaidiMap = new Map(KuaidiData.data.map(({ kind, name }) => [kind, name]));
