export {
  GithubOutline,
  InboxOutline,
  SettingOutline,
  StarFill,
  StarOutline,
  SyncOutline,
  SearchOutline,
  DeleteOutline,
  MenuOutline,
  SmileOutline,
  ClockCircleOutline,
  DownOutline,
  CloseCircleFill,
  CheckCircleFill,
  ExportOutline,
  EditOutline,
  CheckOutline,
  ExclamationCircleOutline,
  CloseOutline,
  QuestionCircleOutline,
  InfoCircleFill,
  PhoneOutline,
  EnvironmentOutline,
  LoadingOutline,
  TeamOutline
} from '@ant-design/icons';
